### ISSUE TITLE
Probably a bug in the comment

### ISSUE THREAD

**Issue by raghavddps2** [piyush97/4thSemIse#8]
[https://github.com/piyush97/4thSemIseCse/blob/master/MicroProcessor%20Lab%20Programs/1A.asm](url)

In this program, in line number 34, shouldn't the comment be **if a[mid] > key** ?
Its written as if a[mid] < key

Correct me if i am wrong.

**Comment by ishank-dev** [comment]
yes, you are right it should be changed..

**Comment by piyush97** [comment]
<details>
<summary>Details</summary>
Status: Resolved
Commit ID: 
ba6cd50057858c6cbea8cebe8bb58fabf2bb2248
</details>
@ishank-dev 	@raghavddps2
